-- MySQL Script generated by MySQL Workbench
-- Thu May 19 00:31:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`empresa` (
  `empNit` VARCHAR(12) NOT NULL,
  `empNombre` VARCHAR(100) NULL,
  `empEstado` INT(1) NULL,
  `empLibre1` VARCHAR(100) NULL,
  PRIMARY KEY (`empNit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`roles` (
  `rolId` INT(2) NOT NULL,
  `rolRol` VARCHAR(50) NULL,
  `rolEstado` INT(1) NULL,
  PRIMARY KEY (`rolId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`usuario` (
  `usrCedula` VARCHAR(12) NOT NULL,
  `usrPrimerNombre` VARCHAR(50) NULL,
  `usrSegundoNombre` VARCHAR(50) NULL,
  `usrPrimerApellido` VARCHAR(50) NULL,
  `usrSegundoApellido` VARCHAR(50) NULL,
  `usrClave` VARCHAR(150) NULL,
  `usrEmail` VARCHAR(50) NULL,
  `usrNitEmpresa` VARCHAR(12) NULL,
  `usrRol` INT(2) NULL,
  `usrEstado` INT(1) NULL,
  PRIMARY KEY (`usrCedula`),
  INDEX `fkEmpresaUsuario_idx` (`usrNitEmpresa` ASC),
  INDEX `fkRolesUsuario_idx` (`usrRol` ASC),
  CONSTRAINT `fkEmpresaUsuario`
    FOREIGN KEY (`usrNitEmpresa`)
    REFERENCES `test`.`empresa` (`empNit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkRolesUsuario`
    FOREIGN KEY (`usrRol`)
    REFERENCES `test`.`roles` (`rolId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
